###
POST http://localhost:8081/cars
Content-Type: application/json

{
  "brand": "bmw",
  "model": "x5",
  "mileage": 10000,
  "passengers": [
    { "name": "Jan" },
    { "name": "Piet" },
    { "name": "Kees" }
  ]
}

###
GET http://localhost:8080/cars
